version: '3'
services:
  emotion-detection:
    image: registry.insight-centre.org/annandas-phd/emotion-detection:latest
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - "./dataset:/app/dataset"
      - "./emotion_detection_system:/app/emotion_detection_system"
    restart: unless-stopped
    working_dir: /app/emotion_detection_system
    entrypoint: sh -c "/app/emotion_detection_system/scripts/data_experiments_batch_01.sh"
#    entrypoint: /bin/sh -c
